---
- name: Set same timezone on every node
  timezone:
    name: "{{ system_timezone }}"
  when: (system_timezone is defined) and (system_timezone != "Your/Timezone")

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes

- name: Install Python Kubernetes library
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip
    - python3-kubernetes

- name: Deploy Longhorn prerequisites
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ lh_packages }}"

- ansible.builtin.include_task: download.yml