---
- name: Install Python Kubernetes library
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip
    - python3-kubernetes

- name: Deploy Longhorn prerequisites
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ lh_packages }}"

- ansible.builtin.include_tasks: download.yaml

- ansible.builtin.include_tasks: ipforwarding.yaml

- ansible.builtin.include_tasks: firewall.yaml